module.exports = [
  {
    date: "April 1",
    source: "Income",
    isThisCredit: true,
    amount: 1000,
    category: "Work",
  },
  {
    date: "April 1",
    source: "Taxes",
    isThisCredit: false,
    amount: -300,
    category: "Bills",
  },
  {
    date: "April 1",
    source: "Retirement",
    isThisCredit: false,
    amount: -200,
    category: "Savings",
  },
  {
    date: "April 1",
    source: "Savings",
    isThisCredit: true,
    amount: false,
    category: "Savings",
  },
  {
    date: "April 1",
    source: "Credit Card Payment",
    isThisCredit: false,
    amount: -100,
    category: "Bills",
  },
  {
    date: "April 5",
    source: "Monthly Birthday Money from Aunt Tilda",
    isThisCredit: true,
    amount: 20,
    category: "Gifts",
  },
  {
    date: "April 5",
    source: "Coffee",
    isThisCredit: false,
    amount: -4,
    category: "Daily Expenses",
  },
  {
    date: "April 5",
    source: "Internet",
    isThisCredit: false,
    amount: -100,
    category: "Bills",
  },
  {
    date: "April 3",
    source: "Groceries",
    isThisCredit: false,
    amount: -76,
    category: "Household Expense",
  },
  {
    date: "April 3",
    source: "Pet Food",
    isThisCredit: false,
    amount: -7,
    category: "Household Expense",
  },
];
